### ISSUE TITLE
Enable XDebug properly

### ISSUE THREAD

**Issue by erickj-ciandt** [ciandt-dev/docker-hub-php#10]
Currently `xdebug.remote_enable` is set to `Off`, which won't allow debugging in any way.

We might have to try enabling `xdebug.remote_connect_back` or setting `xdebug.remote_host` so we can debug code with an IDE from outside the container (https://xdebug.org/docs/remote#starting).

**Comment by rodrigoeg** [comment]
As these changes were already merged into main release, I am closing this issue.
