### ISSUE TITLE
php.ini is being overridden in Dockerfile

### ISSUE THREAD

**Issue by rodrigoeg** [ciandt-dev/docker-hub-php#11]
During the configuration of xdebug, php.ini file is being overridden in Dockerfile:

```
    && echo "zend_extension=/usr/local/php${_PHP_MAJOR_VERSION}/lib/php/extensions/no-debug-non-zts-20131226/xdebug.so" \
        > ${PHP_CONF} \
```

This part needs to be changed to >> instead of using only >

**Comment by ivan-pinatti** [comment]
@rodrigoeg isn't this related to #10 and #1 ?

**Comment by rodrigoeg** [comment]
@ivan-pinatti, it's somewhat related, but it is not the root cause of xdebug not working properly.
