### ISSUE TITLE
PHP had a minor upgrade in Acquia (5.6.28)

### ISSUE THREAD

**Issue by erickj-ciandt** [ciandt-dev/docker-hub-php#9]
In the version 1.96 of its platform release Acquia has upgraded to PHP 5.6.28 - see https://docs.acquia.com/release-note/acquia-cloud-196. We should probably have this upgrade done as well.

**Comment by ivan-pinatti** [comment]
Hi @rodrigoeg,

Could you please take a look at this?

It should be easy.
Just need to change the variable version and update the documentation.

If you need any help please let me know.

**Comment by rodrigoeg** [comment]
Yaml PECL extension was also installed on this version.
Also, please review the versions of all PECL extensions.

**Comment by rodrigoeg** [comment]
PHP and list of extensions upgrated
